INSERT INTO CLIENT (CLIENT_ID, FIRST_NAME, LAST_NAME, TELEPHONE) VALUES (1, 'CICCIO', 'FRANCO', '333333');
INSERT INTO ADDRESS (ADDRESS_ID, CITY, CLIENT_ID, COUNTRY, POSTCODE, STREET) VALUES (1, 'LECCE', 1, 'ITALY', '73100', 'VIA G G');
INSERT INTO PILOTES_ORDER (ORDER_ID, ORDER_TOTAL, PILOTES, ADDRESS_ID) VALUES (1, 3.33, 15, 1);
